source 'http://rubygems.org'
gem 'rails', '4.1.6'
gem 'sqlite3'
gem 'bootstrap-sass'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'haml', '~> 4.0.6'
gem 'simple_form', '~> 3.1.0'
gem 'devise', '~> 3.4.1'
gem 'tzinfo-data'
gem 'mini_magick', '~> 4.1.1'
gem 'carrierwave'
gem 'chosen-rails'
gem 'ransack', '~> 1.7.0'
gem 'kaminari', '~> 0.16.3'
